CREATE TABLE IF NOT EXISTS posts
  ("id" SERIAL PRIMARY KEY,
   "title" TEXT NOT NULL,
   "text" TEXT NOT NULL,
   "categoryId" INT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
   "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
   "authorId" INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
   "isPublished" BOOLEAN NOT NULL);