CREATE TABLE IF NOT EXISTS users
  ("id" SERIAL PRIMARY KEY,
   "name" TEXT NOT NULL,
   "login" TEXT NOT NULL UNIQUE,
   "password" TEXT NOT NULL,
   "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
   "isAdmin" BOOLEAN NOT NULL,
   "isAuthor" BOOLEAN NOT NULL);
